import 'package:uuid/uuid.dart';

const uuid = Uuid();

class Place{
  Place({required this.title}):id=uuid.v4();    //Here we are deriving the id from the uuid package dynamically
  //The id will be autogenerated
  final String title;
  final String id;
}